name: mkUtils
description: mkUtils is a lib for plugins development. By Mikael with help of Eduard and Koddy.
version: 2.0b
api-version: 1.17
load: POSTWORLD
loadbefore: [ WRLDPaymentsAPI ]
authors: [ Mikael, Eduard, Koddy ]
website: "https://github.com/MikaelMaster/mkUtils"
main: com.mikael.mkutils.spigot.UtilsMain

commands:
  mkutils:
    description: Shows mkUtils version.
    usage: /mkutils
    permission: mkutils.defaultperm
  customcrafts:
    aliases:
      - customcraftrecipes
      - customrecipes
    description: Opens a menu with all server custom crafts.
    usage: /customcrafts
    permission: mkutils.cmd.customcrafts