name: mkUtils
version: 1.2.5
api-version: 1.17
load: POSTWORLD
loadbefore: [ WRLDPaymentsAPI ]
author: Mikael
main: com.mikael.mkutils.spigot.UtilsMain

commands:
  mkutils:
    description: Shows mkUtils version.
    usage: /mkutils
    permission: mkutils.defaultperm
  customcrafts:
    aliases:
      - customcraftrecipes
      - customrecipes
    description: Opens a menu with all server custom crafts.
    usage: /customcrafts
    permission: mkutils.cmd.customcrafts