name: mkUtils
version: 1.2.0
api-version: 1.17
load: POSTWORLD
loadbefore: [ WRLDPaymentsAPI ]
author: Mikael
main: com.mikael.mkutils.spigot.UtilsMain

commands:
  mkutils:
    description: Shows mkUtils current version.
    usage: /mkutils
    permission: mkutils.defaultperm
  customcrafts:
    aliases:
      - customcraftrecipes
      - customrecipes
    description: Show all server custom crafts.
    usage: /customcrafts
    permission: mkutils.cmd.customcrafts